// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  CURSOR_SESSIONS: DurableObjectNamespace<
    import("./worker/src/index").CursorSessions
  >;
  RPC_SERVICE: Service<import("./worker/src/index").SessionsRPC>;
}
